project:
  type: website

  preview:
    port: 4321
    browser: true

website:
  title: "Home"
  navbar:
    left:
      - text: Events
        href: content/events/index.qmd
      - text: Team
        href: content/team/index.qmd
      - text: Contact
        href: content/contact.qmd
  sidebar: true

format:
  html:
    theme: cosmo
    linkcolor: "#1565c1"
    mainfont: "Roboto"
    css: ./assets/css/styles.css
    toc: false
    include-after-body: _footer.html
    include-in-header:
      text: |
        <!--
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        -->

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">

        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link rel="preload" as="style" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&family=Roboto+Mono&family=Roboto:wght@400;500;700&display=swap">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&family=Roboto+Mono&family=Roboto:wght@400;500;700&display=swap" media="print" onload="this.media='all'">
