---
title: "[R4DS Summer Study Group 2023]{.event-title}"
subtitle: "[From July through to the end of September 2023 the R User Group at the University of Manchester ran a study group for the 2nd edition of R for Data Science by Hadley Wickham.]{.event-summary} <br> \
[Wed July 12, 2023 - Wed September 27, 2023 @ 4:30 pm - 5:30 pm]{.event-time} <br> \
[Online via Microsoft Teams for the University of Manchester]{.event-location}"
format:
  html:
    anchor-sections: false
date: "2023-07-12"
---

## Background

<!--
date: "2023-07-12T16:30:00"
date_end: "2023-09-27T17:30:00"
event: R Summer Study Group
location: Online via Microsoft Teams for the University of Manchester
publish_date: "2023-09-25T00:00:00" 
-->

Over the months of July, August and September 2023, members of the R User Group at the University of Manchester (RUM) organising committee organised and ran study book club study sessions for the 2nd edition of *R for Data Science* by Hadley Wickham.

### Event

Each week we covered new material from the 2nd edition of [R for Data Science](https://r4ds.hadley.nz/). A volunteer chair ran the study session by welcoming everyone and introduced the new concepts and topics covered. Participants then broke out into groups and shared how they tackled exercises within their groups. The chair wrapped each session with a summary and held space for open questions and conversation.

### Chairs

Date       | Week    | Chair
-----------|---------|----------------------
12/07/2023 | Week 1  | Stavrina Dimosthenous
19/07/2023 | Week 2  | Stavrina Dimosthenous
26/07/2023 | Week 3  | Mychel Morais
02/08/2023 | Week 4  | Kamilla Kopec-Harding
09/08/2023 | Week 5  | Rowan Green
16/08/2023 | Week 6  | Lana Bojanic
23/08/2023 | Week 7  | Kamilla Kopec-Harding
30/08/2023 | Week 8  | Emma Simpson 
06/09/2023 | Week 9  | Martin Herrerias
13/09/2023 | Week 10 | Martin Herrerias
20/09/2023 | Week 11 | Mychel Morais
27/09/2023 | Week 12 | Rowan Green 
