---
title: "[R package development]{.event-title}"
subtitle: "[Glen Martin & Augustin Mutak talk about their experience with R package development.]{.event-summary} <br> \
[Nov 30 2023 @ 12:00 pm - 1:00 pm]{.event-time} <br> \
[Room 3A.057, Engineering A (University of Manchester) [&#8226;]{.sep} Online via Microsoft Teams]{.event-location}"
format:
  html:
    anchor-sections: false
date: "2023-11-30"
---

<!--
date: "2023-11-30T12:00:00"
date_end: "2023-11-30T13:00:00"
event: R User Group Meeting
location: Engineering A 3A.057 &amp; Online via Microsoft Teams
publish_date: "2023-11-08T00:00:00"
-->

Get an overview of how the `predRupdate` was developed and published on CRAN,
and learn about doing analysis with the `cosinor2` package.

**Online Meeting**: \
[Microsoft Teams](https://teams.microsoft.com/l/meetup-join/19%3a7067cf1044b243a4a548d19ef38dd4ca%40thread.tacv2/1699016036662?context=%7b%22Tid%22%3a%22c152cb07-614e-4abb-818a-f035cfa91a77%22%2c%22Oid%22%3a%22a6268e3e-ebaf-4ac7-8498-8dbd4e1c426a%22%7d)  
*The Microsoft Teams chat is only available for members of the University of Manchester, if you want to get in touch write us an email at r-user-group@manchester.ac.uk*

**Talk 1**: *predRupdate and publishing to CRAN* &#8212; speaker **Glen Martin**, Senior Lecturer in Health Data Science, the University of Manchester

***Abstract***: *In this talk I will give a brief overview of the predRupdate package, the stages of creating predRupdate and getting it published on CRAN.*

***Bio***: Dr Glen Martin is a Senior Lecturer in Health Data Science, based in the Centre for Health Informatics at the University of Manchester. He has recently developed an R package for validating and updating clinical prediction models, [predRupdate](https://github.com/GlenMartin31/predRupdate).


**Talk 2**: *Using the cosinor2 Package for R* &#8212; speaker **Augustin Mutak**, Freie Universität Berlin

***Abstract***: *In this talk, attendees will learn about the cosinor model, which allows researchers to fit sinusoidal curves to detect periodicity, about different variants and extensions of the cosinor model and they will be given an overview of the package development. For every specific cosinor method mentioned in the talk, users will also be shown how to perform the corresponding analysis in R using the cosinor2 package.*

***Bio***: Augustin Mutak is a Ph.D. student and a research assistant at Freie Universität Berlin, where he works on development of psychometric models for response times. Prior to that, he graduated psychology in Zagreb and researched fluctuations of mood, for the purpose of which he developed the cosinor2 package for R.
