on:
  workflow_dispatch:
  push:
    branches: [main, dev]

name: Quarto Publish with Optional Staging

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render Site
        run: |
          if [ "${{ github.ref }}" = "refs/heads/dev" ]; then
            quarto render --output-dir dev
          else
            quarto render
          fi

      - name: Publish Site to Live or Staging Area
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: ${{ github.ref == 'refs/heads/dev' && 'dev' || '.' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
